[build]
  publish = "./public"
  functions = "./functions"
  command = "npm run build"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'sha256-v0viTvNBIUjwEskrpGdo05cnJrs0NcuGe+kxIvwr5tE='; script-src 'sha256-5inP/JsVZUvMeScVDp9W/v3v7z1di728zFwAcUiIoK0='; frame-ancestors 'none'"
